eventplanner/eventplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

eventplanner/main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('events/', views.event_index, name='event-index'),
    path('events/<int:event_id>/', views.event_detail, name='event-detail'),
    path('events/create/', views.EventCreate.as_view(), name='event-create'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    path('events/<int:event_id>/add_moment/', views.add_moment, name='add-moment'),
    path('assets/create/', views.AssetCreate.as_view(), name='asset-create'),
    path('assets/<int:pk>/', views.AssetDetail.as_view(), name='asset-detail'),
    path('assets/', views.AssetList.as_view(), name='asset-index'),
    path('assets/<int:pk>/update/', views.AssetUpdate.as_view(), name='asset-update'),
    path('assets/<int:pk>/delete/', views.AssetDelete.as_view(), name='asset-delete'),
    path('events/<int:event_id>/associate-asset/<int:asset_id>/', views.associate_asset, name='associate-toy'),
    path('events/<int:event_id>/remove-asset/<int:asset_id>/', views.remove_asset, name='remove-asset'),
    path('accounts/signup/', views.signup, name='signup'),
]

eventplanner/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Asset(models.Model):
     name = models.CharField(max_length=50)
     description = models.TextField(max_length=150)

     def __str__(self):
          return self.name
     
     def get_absolute_url(self):
        return reverse('asset-detail', kwargs={'pk': self.id})

class Event(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    people = models.IntegerField()
    assets = models.ManyToManyField(Asset)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'event_id': self.id})
    
class Moment(models.Model):
    name = models.CharField(max_length=100)
    date_time = models.DateTimeField('Date & Time')

    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
            return f'{self.name} on {self.date_time}'
    
    class Meta:
         ordering = ['date_time']

eventplanner/main_app/forms.py
from django import forms
from .models import Moment

class MomentForm(forms.ModelForm):
    class Meta:
        model = Moment
        fields = ['name', 'date_time']
        widgets = {
            'date_time': forms.DateInput(
                format=('%Y/%m/%d'),
                attrs={
                    'placeholder': 'Select a date & time',
                    'type': 'datetime-local'
                }
            )
        }

eventplanner/main_app/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Event, Asset
from .forms import MomentForm

class Home(LoginView):
    template_name = 'home.html'

class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    fields = ['name', 'type', 'description', 'people']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['name', 'type', 'description', 'people']

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = '/events/'

class AssetCreate(LoginRequiredMixin, CreateView):
    model = Asset
    fields = '__all__'

class AssetList(LoginRequiredMixin, ListView):
    model = Asset

class AssetDetail(LoginRequiredMixin, DetailView):
    model = Asset

class AssetUpdate(LoginRequiredMixin, UpdateView):
    model = Asset
    fields = '__all__'

class AssetDelete(LoginRequiredMixin, DeleteView):
    model = Asset
    success_url = '/assets/'

# class Event:
#     def __init__(self, name, type, description, people):
#         self.name = name
#         self.type = type
#         self.description = description
#         self.people = people

# events = [
#     Event('Company Meeting', 'Business', 'Discussing business analytics', 25),
#     Event('Basketball Tournament', 'Competition', 'Bracket style basketball tournament', 56),
#     Event('Jones Wedding Reception', 'Ceremony', 'Wedding reception', 200)

# ]

# Create your views here.
# def home(request):
#     return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def event_index(request):
    events = Event.objects.filter(user=request.user)
    return render(request, 'events/index.html', {'events': events})

@login_required
def event_detail(request, event_id):
    event = Event.objects.get(id=event_id)
    assets_event_doesnt_have = Asset.objects.exclude(id__in = event.assets.all().values_list('id'))
    moment_form = MomentForm()
    return render(request, 'events/detail.html', {
        'event': event, 
        'moment_form': moment_form,
        'assets': assets_event_doesnt_have
        })

@login_required
def add_moment(request, event_id):
    form = MomentForm(request.POST)
    if form.is_valid():
        new_moment = form.save(commit=False)
        new_moment.event_id = event_id
        new_moment.save()
    return redirect('event-detail', event_id=event_id)

@login_required
def associate_asset(request, event_id, asset_id):
    Event.objects.get(id=event_id).assets.add(asset_id)
    return redirect('event-detail', event_id=event_id)

@login_required
def remove_asset(request, event_id, asset_id):
    Event.objects.get(id=event_id).assets.remove(asset_id)
    return redirect('event-detail', event_id=event_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('event-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error-message': error_message}
    return render(request, 'signup.html', context)

eventplanner/main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Event Planner App</h1>
<hr />
<p class="page-content">
  Compiling Events and details about them!
</p>
{% endblock %}

eventplanner/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Event Planner</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
            <img src="" alt="Event Planner App Logo" />
        </a>
      </div>
      <nav>
        <ul>
          
          {% if user.is_authenticated %}
          <li><a href="{% url 'event-index' %}">All Events</a></li>
          <li><a href="{% url 'asset-index' %}">All Assets</a></li>
          <li><a href="{% url 'event-create' %}">Add an Event</a></li>
          <li><a href="{% url 'asset-create' %}">Add an Asset</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}            
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

eventplanner/main_app/templates/events/detail.html
{% extends 'base.html' %} 
{% block content %}

<section>
    <div>
        <h1>{{ event.type }}</h1>
          <h2>{{ event.name }}</h2>
        <h3>{{ event.description }}</h3>
        <p>{{ event.people }} people currently attending!</p>
      </div>
    <div>
      <a href="{% url 'event-update' event.id %}">Edit</a>
      <a href="{% url 'event-delete' event.id %}">Delete</a>
    </div>
</section>

<h3>Add a Moment</h3>
<!-- Add just above the feedings table -->
<form action="{% url 'add-moment' event.id %}" method='POST' autocomplete="off">
  {% csrf_token %} 
  {{ moment_form.as_p }}
  <button type="submit">Add Moment</button>
</form>


<div>
  <section>
    <div>
      <h2>Moments</h2>
    </div>
    {% if event.moment_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Moment</th>
          <th>Date & Time</th>
        </tr>
      </thead>
      <tbody>
        {% for moment in event.moment_set.all %}
          <tr>
            <td>{{moment.name}}</td>
            <td>{{moment.date_time}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div>
      <p>No moments created for this event yet!</p>
    </div>
    {% endif %}
  </section>
</div>

<section>
  <div>
    <h2>Assets</h2>
  </div>

  <h3>Requested Assets</h3>
  <div>
    {% if event.assets.count %} 
      {% for asset in event.assets.all %}
        <div>
          <a href="{% url 'asset-detail' asset.id %}">
            <p>{{ asset.name }}</p>
            <form action="{% url 'remove-asset' event.id asset.id %}" method="post">
              {% csrf_token %}
              <button type="submit">Remove Asset</button>
            </form>
            
          </a>
        </div>
      {% endfor %} 
    {% else %}
      <p>Request some assets for this event if needed!</p>
    {% endif %}
  </div>

  <h3>Available Assets</h3>
  <div>
    {% for asset in assets %}
      <div>
        <p>{{ asset.name }}</p>
        <form action="{% url 'associate-toy' event.id asset.id %}" method="post">
          {% csrf_token %}
          <button type="submit">Use Asset</button>
        </form>
      </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

eventplanner/main_app/templates/events/index.html
{% extends 'base.html' %} 
{% block content %}

<section class="page-header">
    <h1>Event List</h1>
</section>

<section>
    
    {% for event in events %}
    <div>
        <a href="{% url 'event-detail' event.id %}">
         <h2>{{ event.name }}</h2>
        </a>    
    </div>
    {% endfor %}
        
</section>

{% endblock %}

eventplanner/main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="page-header">
  <div>
    <h1>Events, Events, Events!</h1>
  </div>
</section>


{% if not user.is_authenticated %} 
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

eventplanner/main_app/templates/main_app/asset_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Asset?</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'asset-detail' asset.id %}"> Cancel </a>
  <button type="submit">Yes - Delete!</button>
</form>

{% endblock %}

eventplanner/main_app/templates/main_app/asset_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}

<div>
  <div>
    <h2>{{ asset.name }}</h2>
    <p>{{ asset.description }}</p>
  </div>
</div>
<a href="{% url 'asset-update' asset.id %}">Edit</a>
<a href="{% url 'asset-delete' asset.id %}">Delete</a>

{% endblock %}

eventplanner/main_app/templates/main_app/asset_form.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add an Asset</h1>
    {% endif %}
  </div>
  <form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Submit!</button>
  </form>

{% endblock %}

eventplanner/main_app/templates/main_app/asset_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}

<section class="page-header">
  <h1>All Assets</h1>
</section>

<section class="card-container">
  {% for asset in asset_list %}
    <div>
      <a href="{% url 'asset-detail' asset.id %}">
        <div>
          <h2>{{ asset.name }}</h2>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

eventplanner/main_app/templates/main_app/event_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div>
  <h1>Delete Event?</h1>
</div>

<h2>Are you sure you want to delete {{ event.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'event-detail' event.id %}">Cancel</a>
  <button type="submit">Yes - Delete!</button>
</form>

{% endblock %}

eventplanner/main_app/templates/main_app/event_form.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}

<div class="page-header">
    {% if event %}
        <h1>Edit {{ event.name }}</h1>
    {% else %}
        <h1>Add an Event</h1>
    {% endif %}
</div>

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit">Submit!</button>
</form>

{% endblock %}

eventplanner/main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}